# Generated by Django 5.1.2 on 2024-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
